language: java

jdk:
  - openjdk11

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test sonar:sonar -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - docker

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - mvn -P assemble-jars package -B
  - DOCKERTAG="${TRAVIS_TAG:1}-${TRAVIS_COMMIT:0:7}"
  - SEMVER=( ${DOCKERTAG//./ } )
  - docker build --build-arg PATH_TO_LIB=./api/target/libs/ -t ${DOCKER_USERNAME}/jms-social-media --label "commit=$TRAVIS_COMMIT" --label "version=${TRAVIS_TAG:1}" --label "tag=$DOCKERTAG" .
  - docker tag ${DOCKER_USERNAME}/jms-social-media ${DOCKER_USERNAME}/jms-social-media:${DOCKERTAG}
  - docker tag ${DOCKER_USERNAME}/jms-social-media ${DOCKER_USERNAME}/jms-social-media:${SEMVER[0]}
  - docker tag ${DOCKER_USERNAME}/jms-social-media ${DOCKER_USERNAME}/jms-social-media:"${SEMVER[0]}.${SEMVER[1]}"

deploy:
  provider: script
  script: docker push ${DOCKER_USERNAME}/jms-social-media:${DOCKERTAG} && docker push ${DOCKER_USERNAME}/jms-social-media:${SEMVER[0]} && docker push ${DOCKER_USERNAME}/jms-social-media:"${SEMVER[0]}.${SEMVER[1]}" && docker push ${DOCKER_USERNAME}/jms-social-media:latest
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "jasonsarwar-github"
    token:
      secure: "$SONAR_TOKEN"

notifications:
  webhooks: $DISCORD_WEBHOOK
