language: java

jdk:
  - openjdk11

install: 
  - mvn install:install-file -Dfile=core/lib/ojdbc6.jar -DgroupId=oracle -DartifactId=ojdbc6 -Dversion=11.2.0.3 -Dpackaging=jar install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2